steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/healthcare-chatbot-website:$COMMIT_SHA'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/healthcare-chatbot-website:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
